int32 action_type
float32 control_signal_ankle
float32 control_signal_knee
################################
float32 position_desired_ankle
float32 position_desired_knee
float32 position_actual_ankle
float32 position_actual_knee
float32 velocity_actual_ankle
float32 velocity_actual_knee
float32 velocity_desired_ankle
float32 velocity_desired_knee
float32 torque_desired_ankle
float32 torque_desired_knee
float32 torque_actual_ankle
float32 torque_actual_knee
float32 torque_imped_ankle
float32 torque_imped_knee
float32 tau
float32 ishumanswing
################################
float32 force_toe
float32 force_heel
################################
float32 imu_position_ankle
float32 imu_position_knee
float32 imu_velocity_ankle
float32 imu_velocity_knee
################################
float32 imu_thigh_pos
float32 imu_thigh_vel
